---
kind: pipeline
name: amd64
type: docker

platform:
  os: linux
  arch: amd64

steps:
  - name: build
    image: rancher/dapper:v0.6.0
    environment:
      OAUTH_TOKEN:
        from_secret: github_token
    commands:
      - dapper ci
    volumes:
      - name: docker
        path: /var/run/docker.sock

  - name: integration-test
    image: rancher/rancher:v2.7-head
    privileged: true
    commands:
      - scripts/integration-test

  - name: github_binary_release
    image: plugins/github-release
    settings:
      api_key:
        from_secret: github_token
      prerelease: true
      checksum:
        - sha256
      checksum_file: CHECKSUMsum-amd64.txt
      checksum_flatten: true
      files:
        - "dist/artifacts/*"
    when:
      ref:
        - refs/head/master
        - refs/tags/*
      event:
        - tag

  - name: docker-publish
    image: plugins/docker
    settings:
      dockerfile: package/Dockerfile
      password:
        from_secret: docker_password
      repo: "cnrancher/rancher-webhook"
      tag: "${DRONE_TAG}-amd64"
      username:
        from_secret: docker_username
    when:
      ref:
        - refs/head/master
        - refs/tags/*
      event:
        - tag
volumes:
  - name: docker
    host:
      path: /var/run/docker.sock

node:
  instance: agent-amd64

---
kind: pipeline
name: arm64
type: docker

platform:
  os: linux
  arch: arm64

steps:
  - name: build
    image: rancher/dapper:v0.6.0
    environment:
      OAUTH_TOKEN:
        from_secret: github_token
    commands:
      - dapper ci
    volumes:
      - name: docker
        path: /var/run/docker.sock

  - name: integration-test
    image: rancher/rancher:v2.7-head
    privileged: true
    commands:
      - scripts/integration-test

  - name: github_binary_release
    image: plugins/github-release
    settings:
      api_key:
        from_secret: github_token
      prerelease: true
      checksum:
        - sha256
      checksum_file: CHECKSUMsum-arm64.txt
      checksum_flatten: true
      files:
        - "dist/artifacts/*"
    when:
      ref:
        - refs/head/master
        - refs/tags/*
      event:
        - tag

  - name: docker-publish
    image: plugins/docker
    settings:
      dockerfile: package/Dockerfile
      password:
        from_secret: docker_password
      repo: "cnrancher/rancher-webhook"
      tag: "${DRONE_TAG}-arm64"
      username:
        from_secret: docker_username
    when:
      ref:
        - refs/head/master
        - refs/tags/*
      event:
        - tag

volumes:
  - name: docker
    host:
      path: /var/run/docker.sock

node:
  instance: agent-arm64

---
kind: pipeline
name: manifest
type: docker

platform:
  os: linux
  arch: amd64

steps:
  - name: manifest
    image: plugins/manifest:1.0.2
    settings:
      username:
        from_secret: docker_username
      password:
          from_secret: docker_password
      platforms:
        - linux/amd64
        - linux/arm64
      target: "cnrancher/rancher-webhook:${DRONE_TAG}"
      template: "cnrancher/rancher-webhook:${DRONE_TAG}-ARCH"
    when:
      ref:
        - refs/head/master
        - refs/tags/*
      event:
        - tag

node:
  instance: agent-amd64

depends_on:
  - amd64
  - arm64
